### ISSUE TITLE
Signer-CLI tx submit error

### ISSUE THREAD

**Issue by ansonla3** [polkadot-js/tools#120]
When executing with

```
 polkadot-js-api --seed "xxxxx xxxxxxxxxxx xxxxxx" tx.staking.nominate ["CmD9vaMYoiKe7HiFnfkftwvhKbxN9bhyjcDrfFRGbifJEG8"] --ws wss://kusama-rpc.polkadot.io/
```

Result:

```
Error: createType(Call):: Struct: failed on 'args':: Struct: failed on 'targets':: Vec length 157953272386962967567130957269530289354615815086130816564358467 exceeds 32768
    at createTypeUnsafe (/Users/anson/.nvm/versions/node/v13.8.0/lib/node_modules/@polkadot/api-cli/node_modules/@polkadot/types/create/createType.js:68:11)
    at createType (/Users/anson/.nvm/versions/node/v13.8.0/lib/node_modules/@polkadot/api-cli/node_modules/@polkadot/types/create/createType.js:80:10)
    at TypeRegistry.createType (/Users/anson/.nvm/versions/node/v13.8.0/lib/node_modules/@polkadot/api-cli/node_modules/@polkadot/types/create/registry.js:187:39)
    at extrinsicFn (/Users/anson/.nvm/versions/node/v13.8.0/lib/node_modules/@polkadot/api-cli/node_modules/@polkadot/metadata/Decorated/extrinsics/fromMetadata/createUnchecked.js:22:21)
    at decorated (/Users/anson/.nvm/versions/node/v13.8.0/lib/node_modules/@polkadot/api-cli/node_modules/@polkadot/api/base/Decorate.js:265:46)
    at makeTx (/Users/anson/.nvm/versions/node/v13.8.0/lib/node_modules/@polkadot/api-cli/api.js:184:16)
    at main (/Users/anson/.nvm/versions/node/v13.8.0/lib/node_modules/@polkadot/api-cli/api.js:219:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

**Comment by jacogr** [comment]
Unlike the api-cli, the signer doesn't actually handle JSON inputs -

https://github.com/polkadot-js/tools/blob/master/packages/api-cli/src/api.ts#L85
