### ISSUE TITLE
Error when using run:api 

### ISSUE THREAD

**Issue by ansonla3** [polkadot-js/tools#124]
Already downloaded the latest release but still getting the following error

```
 yarn run:api --seed "abcdedfg" tx.staking.nominate ["CmD9vaMYoiKe7HiFnfkftwvhKbxN9bhyjcDrfFRGbifJEG8"] --ws wss://kusama-rpc.polkadot.io/
```

Result:

```
Error: createType(Call):: Struct: failed on 'args':: Struct: failed on 'targets':: Vec length 157953272386962967567130957269530289354615815086130816564358467 exceeds 32768
    at createTypeUnsafe (/Users/anson/tools/node_modules/@polkadot/types/create/createType.js:68:11)
    at createType (/Users/anson/tools/node_modules/@polkadot/types/create/createType.js:80:10)
    at TypeRegistry.createType (/Users/anson/tools/node_modules/@polkadot/types/create/registry.js:187:39)
    at extrinsicFn (/Users/anson/tools/node_modules/@polkadot/metadata/Decorated/extrinsics/fromMetadata/createUnchecked.js:22:21)
    at fn (/Users/anson/tools/node_modules/@polkadot/api/base/Decorate.js:289:46)
    at makeTx (/Users/anson/tools/packages/api-cli/src/api.ts:192:16)
    at main (/Users/anson/tools/packages/api-cli/src/api.ts:227:12)
```

**Comment by jacogr** [comment]
You need to make sure the shell doesn't expand thing either. So for my specific shell This works for arrays -

`["CmD9vaMYoiKe7HiFnfkftwvhKbxN9bhyjcDrfFRGbifJEG8"]'`

Not the single quotes that tells it to be left alone.

**Comment by ansonla3** [comment]
@jacogr great. thanks
