### ISSUE TITLE
api-cli: unable to resolve types used in substrate kitchen recipes

### ISSUE THREAD

**Issue by coriolinus** [polkadot-js/tools#132]
Running an unmodified local instance of the [`kitchen-node`](https://github.com/substrate-developer-hub/recipes/tree/master/nodes/kitchen-node), I attempted to send a very basic transaction:

```
coriolinus@brubuntu ~/Documents/Projects/substrate-developer-hub/recipes
$ polkadot-js-api --seed "//Alice" tx.hello-substrate.say_hello
Thu 30 Apr 2020 04:50:46 PM CEST
Unable to resolve type GroupIndex, it will fail on construction
Unable to resolve type TaskId, it will fail on construction
Unable to resolve type PriorityScore, it will fail on construction
Unable to resolve type U16F16, it will fail on construction
Unknown types found, no types for BufferIndex,ContinuousAccountData,GroupIndex,InnerThingOf,PriorityScore,RoundIndex,SuperThing,Task,TaskId,U16F16,ValueStruct
2020-04-30 16:50:47        API/INIT: Error: FATAL: Unable to initialize the API: createType(GroupIndex):: Cannot construct unknown type GroupIndex
    at EventEmitter.value (/home/coriolinus/.config/yarn/global/node_modules/@polkadot/api/base/Init.js:67:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: FATAL: Unable to initialize the API: createType(GroupIndex):: Cannot construct unknown type GroupIndex
    at EventEmitter.value (/home/coriolinus/.config/yarn/global/node_modules/@polkadot/api/base/Init.js:67:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I do not know how type resolution proceeds or where it is used, but I am moderately confident that it should not be required for this transaction; the call is [extremely simple](https://github.com/substrate-developer-hub/recipes/blob/cab7577f4401a1331ddf4fe8049a8eb42576f7ef/pallets/hello-substrate/src/lib.rs#L24-L36):

```rust
		#[weight = SimpleDispatchInfo::default()]
		pub fn say_hello(origin) -> DispatchResult {
			// Ensure that the caller is a regular keypair account
			let caller = ensure_signed(origin)?;


			// Print a message
			print("Hello World");
			// Inspecting a variable as well
			debug::info!("Request sent by: {:?}", caller);


			// Indicate that this call succeeded
			Ok(())
		}
```

```
coriolinus@brubuntu ~/Documents/Projects/substrate-developer-hub/recipes
$ polkadot-js-api --version
Thu 30 Apr 2020 04:52:03 PM CEST
0.11.1
```

**Comment by jacogr** [comment]
For the substrate recipes, it is actually needed. The node-template config does not match that of Substrate node - https://polkadot.js.org/api/start/FAQ.html#i-cannot-send-transactions-from-my-node-template-based-chain

**Comment by jacogr** [comment]
Closing.
