### ISSUE TITLE
TypeError: param.startsWith is not a function thrown with tx.staking.bond

### ISSUE THREAD

**Issue by wpank** [polkadot-js/tools#177]
Running the following command from a docker container:

`docker run --network=host jacogr/polkadot-js-tools api tx.staking.bond --seed "//Charlie" 5FLS
igC9HGRKVhB9FiEo4Y3koPsNmBmLJbpXg2mp1hXcS59Y 10000000000000 Staked`

Results in the following error being thrown:

```
/usr/lib/node_modules/@polkadot/api-cli/node_modules/yargs/build/index.cjs:2756
                throw err;
                ^

TypeError: param.startsWith is not a function
    at argv._.argv._.map.param (/usr/lib/node_modules/@polkadot/api-cli/cli.js:30:15)
    at Array.map (<anonymous>)
    at hexMiddleware (/usr/lib/node_modules/@polkadot/api-cli/cli.js:29:19)
    at middlewares.reduce (/usr/lib/node_modules/@polkadot/api-cli/node_modules/yargs/build/index.cjs:234:28)
    at Array.reduce (<anonymous>)
    at applyMiddleware (/usr/lib/node_modules/@polkadot/api-cli/node_modules/yargs/build/index.cjs:221:24)
    at Object.runCommand (/usr/lib/node_modules/@polkadot/api-cli/node_modules/yargs/build/index.cjs:432:25)
    at Object.parseArgs [as _parseArgs] (/usr/lib/node_modules/@polkadot/api-cli/node_modules/yargs/build/index.cjs:2690:53)
    at Object.get [as argv] (/usr/lib/node_modules/@polkadot/api-cli/node_modules/yargs/build/index.cjs:2635:25)
    at Object.<anonymous> (/usr/lib/node_modules/@polkadot/api-cli/api.js:67:3)
```

**Comment by jacogr** [comment]
Quite possibly the number is "helpfully" converted - should not be since that hole was closed... So would try with an explicit `"10000000000000"` (quotes around).

However need to take a look as to where/what.

**Comment by jacogr** [comment]
Yes, indeed, it despite the number override here https://github.com/polkadot-js/tools/blob/master/packages/api-cli/src/api.ts#L110 - it seems the type is a number (confirmed). Ok, so will go digging to see in the args parser why that is now not working anymore.
