### ISSUE TITLE
Feature request: cli: Disable unknown types without entirely bailing

### ISSUE THREAD

**Issue by coriolinus** [polkadot-js/tools#185]
I am attempting to automate a two-node local net with parachain. Proper automation means the parachain is automatically registered when the script is run. Registering the parachain looks like this:

```sh
polkadot-js-api \
  --ws ws://localhost:9944 \
  --sudo \
  --seed "//Alice" \
  tx.registrar.registerPara \
    100 \
    '{"scheduling":"Always"}' \
    "@$validation_code" \
    "@$genesis_state"
```

Unfortunately, this produces the following error:

```bash
2020-11-17 16:13:46        METADATA: Unknown types found, no types for AvailabilityBitfieldRecord, BackedCandidate, BufferedSessionChange, CandidatePendingAvailability, CoreAssignment, CoreOccupied, HostConfiguration, HrmpChannel, HrmpChannelId, HrmpOpenChannelRequest, InboundDownwardMessage, InboundHrmpMessage, ParathreadClaimQueue, SignedAvailabilityBitfields, VecDeque
2020-11-17 16:13:46        REGISTRY: Unable to resolve type HrmpChannelId, it will fail on construction
2020-11-17 16:13:46        REGISTRY: Error: Cannot construct unknown type HrmpChannelId
    at new DoNotConstruct (/usr/local/share/.config/yarn/global/node_modules/@polkadot/types/primitive/DoNotConstruct.js:21:11)
    at new <anonymous> (/usr/local/share/.config/yarn/global/node_modules/@polkadot/types/primitive/DoNotConstruct.js:27:9)
    at new Type (/usr/local/share/.config/yarn/global/node_modules/@polkadot/types/create/registry.js:300:16)
    at initType (/usr/local/share/.config/yarn/global/node_modules/@polkadot/types/create/createType.js:49:19)
    at createTypeUnsafe (/usr/local/share/.config/yarn/global/node_modules/@polkadot/types/create/createType.js:68:12)
    at createType (/usr/local/share/.config/yarn/global/node_modules/@polkadot/types/create/createType.js:83:10)
    at TypeRegistry.createType (/usr/local/share/.config/yarn/global/node_modules/@polkadot/types/create/registry.js:257:39)
    at extendHeadMeta (/usr/local/share/.config/yarn/global/node_modules/@polkadot/metadata/decorate/storage/createFunction.js:144:53)
    at extendPrefixedMap (/usr/local/share/.config/yarn/global/node_modules/@polkadot/metadata/decorate/storage/createFunction.js:169:23)
    at createFunction (/usr/local/share/.config/yarn/global/node_modules/@polkadot/metadata/decorate/storage/createFunction.js:192:5)
2020-11-17 16:13:46        API/INIT: Error: FATAL: Unable to initialize the API: createType(HrmpChannelId):: Cannot construct unknown type HrmpChannelId
    at EventEmitter.value (/usr/local/share/.config/yarn/global/node_modules/@polkadot/api/base/Init.js:87:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at processImmediate (internal/timers.js:434:9)
2020-11-17 16:13:46        API/INIT: Error: createType(HrmpChannelId):: Cannot construct unknown type HrmpChannelId
    at createTypeUnsafe (/usr/local/share/.config/yarn/global/node_modules/@polkadot/types/create/createType.js:71:11)
    at createType (/usr/local/share/.config/yarn/global/node_modules/@polkadot/types/create/createType.js:83:10)
    at TypeRegistry.createType (/usr/local/share/.config/yarn/global/node_modules/@polkadot/types/create/registry.js:257:39)
    at extendHeadMeta (/usr/local/share/.config/yarn/global/node_modules/@polkadot/metadata/decorate/storage/createFunction.js:144:53)
    at extendPrefixedMap (/usr/local/share/.config/yarn/global/node_modules/@polkadot/metadata/decorate/storage/createFunction.js:169:23)
    at createFunction (/usr/local/share/.config/yarn/global/node_modules/@polkadot/metadata/decorate/storage/createFunction.js:192:5)
    at /usr/local/share/.config/yarn/global/node_modules/@polkadot/metadata/decorate/storage/fromMetadata.js:38:91
    at Array.reduce (<anonymous>)
    at /usr/local/share/.config/yarn/global/node_modules/@polkadot/metadata/decorate/storage/fromMetadata.js:36:39
    at Array.reduce (<anonymous>)
Error: FATAL: Unable to initialize the API: createType(HrmpChannelId):: Cannot construct unknown type HrmpChannelId
    at EventEmitter.value (/usr/local/share/.config/yarn/global/node_modules/@polkadot/api/base/Init.js:87:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at runNextTicks (internal/process/task_queues.js:66:3)
    at processImmediate (internal/timers.js:434:9)
```

It looks like the fatal issue for the moment is `HrmpChannelId`, with 14 other types unknown. I don't want to need to specify all 15 of those types manually on the command line, even within the script. None of them are relevant to the TX I want to send. Some of them are, I suspect, unspecifiable on the command line, as they contain channels, which are not representable in JSON.

An ideal solution would be a flag like `--ignore-unknown-types` which simply disabled all API endpoints whose types could not be initialized. A somewhat worse solution would be to manually disable certain types with a flag like `--types '{"HrmpChannelId": null}'`, with API endpoints requiring those endpoints disabled. The status quo, where users are required to manually specify all types in the entire API in order to use any endpoint, is pretty onerous.

**Comment by jacogr** [comment]
Sadly, this is a wontfix. Since the issue doesn't sit here at all and this is not changin on the API layer since invalid decodings is worse than anything else. 

In the case of that type, it actually occurs in either an extrinsic, even or metadata as used, hence trying to be constructed. So it is already in-use when it fails. (It just warns and only fails on using)

You can ignore the inknown for all intents and purposes, but you cannot ignore the one where it is constructed.

**Comment by rphmeier** [comment]
@jacogr Can you expand a little bit? Isn't the JS-API supposed to get the types automatically from the metadata? Are you saying that the metadata is malformed?

**Comment by jacogr** [comment]
No. We only get names from metadata, not types. So we know for instance that module X has a type names ABC, but not what that type looks like.

If you want reflection, that is ink! - the ABI is fully described with how each type looks. In Substrate, you have a name.

**Comment by rphmeier** [comment]
How are we intended to provide these types? i.e. if the issue here is a 'wontfix', how are the new runtimes ever supposed to work with polkadot-js?

**Comment by jacogr** [comment]
You define them and pass them to the API, like anything works with the API. 

The issue for support on that has been open for > 1 year now, see https://github.com/polkadot-js/tools/issues/9

**Comment by rphmeier** [comment]
Thank you!

**Comment by jacogr** [comment]
Closing #9 has been addressed.
