### ISSUE TITLE
query.[module].[function].entries support for entries or keys 

### ISSUE THREAD

**Issue by dappdever** [polkadot-js/tools#223]
When querying the DID pallet attributeNonce storage map/function using the UI, the entries are printed (see screenshot).  However, when doing the same with the CLI, I receive the below error.  Using v3 of substrate. 

The storage definition from pallet DID this: 
``` rust
/// Attribute nonce used to generate a unique hash even if the attribute is deleted and recreated.
pub AttributeNonce get(fn nonce_of): map hasher(twox_64_concat) (T::AccountId, Vec<u8>) => u64;
```

Here is Element chat on the matter: https://matrix.to/#/!HzySYSaIhtyWrwiwEV:matrix.org/$16161900411781ctEUT:matrix.parity.io?via=matrix.parity.io&via=matrix.org&via=corepaper.org

Screenshot of UI showing the entries being printed:
![image](https://user-images.githubusercontent.com/32852271/111845715-cdfc2000-88db-11eb-9b0f-08126ecad047.png)

Error message when attempting the same thing from the CLI:
```
polkadot-js-api query.palletDid.attributeNonce.entries                                                                       1   8370ddd 
2021-03-19 17:41:55        REGISTRY: Unable to resolve type AttributeTransaction, it will fail on construction
2021-03-19 17:41:55        METADATA: Unknown types found, no types for Attribute, AttributeTransaction
Error: palletDid.attributeNonce((AccountId,Bytes)) is a map, requiring 1 argument, 0 found
    at assert (/Users/max/.nvm/versions/node/v12.18.2/lib/node_modules/@polkadot/api-cli/node_modules/@polkadot/util/assert.js:34:11)
    at doMap (/Users/max/.nvm/versions/node/v12.18.2/lib/node_modules/@polkadot/api-cli/node_modules/@polkadot/api/util/validate.js:33:20)
    at extractStorageArgs (/Users/max/.nvm/versions/node/v12.18.2/lib/node_modules/@polkadot/api-cli/node_modules/@polkadot/api/util/validate.js:46:12)
    at overrideNoSub (/Users/max/.nvm/versions/node/v12.18.2/lib/node_modules/@polkadot/api-cli/node_modules/@polkadot/api/base/Decorate.js:418:99)
    at /Users/max/.nvm/versions/node/v12.18.2/lib/node_modules/@polkadot/api-cli/node_modules/@polkadot/api/promise/index.js:73:26
    at new Promise (<anonymous>)
    at decorateCall (/Users/max/.nvm/versions/node/v12.18.2/lib/node_modules/@polkadot/api-cli/node_modules/@polkadot/api/promise/index.js:69:10)
    at /Users/max/.nvm/versions/node/v12.18.2/lib/node_modules/@polkadot/api-cli/node_modules/@polkadot/api/promise/index.js:101:73
    at makeCall (/Users/max/.nvm/versions/node/v12.18.2/lib/node_modules/@polkadot/api-cli/api.js:187:8)
    at main (/Users/max/.nvm/versions/node/v12.18.2/lib/node_modules/@polkadot/api-cli/api.js:204:10)
    ```

**Comment by dappdever** [comment]
Hi @jacogr - I am back to working on this. Any update on this? If you can provide a little direction, I can put a PR together. thanks

**Comment by jacogr** [comment]
The problem seems here - https://github.com/polkadot-js/tools/blob/master/packages/api-cli/src/api.ts#L185

it uses `query.palletDid.attributeNonce` and never `.entries` (i.e. by default doesn't seem to support `.keys` or `.entries`.

So for quick and dirty -

- add an additional param in the split linked above
- if a query (only on queries) and the additional param is `keys` or `entries` do `api[type][section][method][extra]` here https://github.com/polkadot-js/tools/blob/master/packages/api-cli/src/api.ts#L191

(For bonus on query we could also cater for `.size` and `.hash` and `.at` to make it more rounded)

**Comment by didiermis** [comment]
@jacogr Hey, I'm struggling with the same issue, any updates? 
Could you repost the links from above? I think they were moved.

**Comment by jacogr** [comment]
This is where the parts are split - https://github.com/polkadot-js/tools/blob/ed3c79339aac4a9469a8474bc8484ddd4055647b/packages/api-cli/src/runcli.ts#L187

**Comment by ap211unitech** [comment]
I think it's fair to consider this issue stale, as there hasn't been any activity for a long time. I'm closing it for now, but if the issue still persists, feel free to comment and I’ll be happy to reopen it.
