### ISSUE TITLE
Signer: simple test won't work

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/tools#239]
I'm trying the first command suggested in the readme and I get 

``` 
yarn run:signer submit --account 5HNHXTw65dTNVGRdYkxFUpKcvmUYQMZHcDHmSKpuC8pvVEaN --ws wss://poc3-rpc.polkadot.io/ balances.transfer 5DkQbYAExs3M2sZgT1Ec3mKfZnAQCL4Dt9beTCknkCUn5jzo 123
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module './cmdSendOffline.cjs'
Require stack:
- /Users/antoineestienne/Github_Files/tools/packages/signer-cli/src/signer.ts
- /Users/antoineestienne/Github_Files/tools/packages/signer-cli/src/index.cjs
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/antoineestienne/Github_Files/tools/packages/signer-cli/src/signer.ts:8:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module._compile (/Users/antoineestienne/Github_Files/tools/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.newLoader [as .ts] (/Users/antoineestienne/Github_Files/tools/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/antoineestienne/Github_Files/tools/packages/signer-cli/src/signer.ts',
    '/Users/antoineestienne/Github_Files/tools/packages/signer-cli/src/index.cjs'
  ]
}

**Comment by joelamouche** [comment]
This is still a problem afaik

**Comment by joelamouche** [comment]
@jacogr fyi the url in the readme is deprecated `wss://poc3-rpc.polkadot.io/`
