### ISSUE TITLE
polkadot-js-tools compare no longer working

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/tools#359]
```
Status: Image is up to date for jacogr/polkadot-js-tools:latest
internal/modules/cjs/loader.js:1102
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /usr/lib/node_modules/@polkadot/metadata-cmp/node_modules/@substrate/connect/dist/index.js
require() of ES modules is not supported.
require() of /usr/lib/node_modules/@polkadot/metadata-cmp/node_modules/@substrate/connect/dist/index.js from /usr/lib/node_modules/@polkadot/metadata-cmp/node_modules/@polkadot/rpc-provider/substrate-connect/ScProvider.cjs is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /usr/lib/node_modules/@polkadot/metadata-cmp/node_modules/@substrate/connect/package.json.

    at new NodeError (internal/errors.js:3[22](https://github.com/paritytech/cumulus/runs/5734463134?check_suite_focus=true#step:7:22):7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:[32](https://github.com/paritytech/cumulus/runs/5734463134?check_suite_focus=true#step:7:32))
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/usr/lib/node_modules/@polkadot/metadata-cmp/node_modules/@polkadot/rpc-provider/substrate-connect/ScProvider.cjs:10:16)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'ERR_REQUIRE_ESM'
```

**Comment by jacogr** [comment]
That was fixed in an API patch aka https://github.com/polkadot-js/api/issues/4692, but not included here... i knew I missed a beat.

Will update now, sorry.
